### ISSUE TITLE
Reason syntax does not mesh well with the new bs.return attribute

### ISSUE THREAD

**Issue by glennsl** [facebook/reason#1115] opened 2017-03-06 18:20 UTC
The new `bs.return` FFI attribute uses this syntax in ml: `[@@bs.return {null_to_opt}]`. In Reason, due to the block/record ambiguity, this syntax will be translated to `[@@bs.return null_to_opt]` which causes the compiler to raise the error "this is not a valid record config". The correct syntax in Reason is `[@@bs.return {null_to_opt: null_to_opt}]`, but this is a tad verbose I think.

cc @bobzhang

**Comment by IwanKaramazow** [comment] 2017-03-06 20:12
It probably wouldn't be that much of a hassle to parse `[@@bs.return null_to_opt]` into `[@@bs.return {null_to_opt: null_to_opt}]`. Or maybe we could snow some sugar on it like `[@@bs.return {"null_to_opt"}]` to make it more consistent with `bs.obj`...

@chenglou bad idea?

**Comment by bobzhang** [comment] 2017-03-07 18:47
note I made an exception for it, so you can write both [@@bs.return null_to_opt] and [@@bs.return {null_to_opt} ] , the latter is more future proof in case we add more properties

**Comment by chenglou** [comment] 2017-03-07 23:56
#1317 is a dupe of this, sorry. Solved!

**Closed by chenglou** 2017-03-07 23:56 UTC
