### ISSUE TITLE
Fast pipe new syntax `->` doesn't seem to replace old syntax `|.` some times

### ISSUE THREAD

**Issue by ryuheechul** [facebook/reason#2249] opened 2018-10-27 07:19 UTC
It's originally discussed [here](https://dev.to/ryuheechul/comment/65ma)

I found something interesting and it's probably a bug.

`->` doesn't work after `|>` when `|.` still works after `|>`

[click to see the proof](https://reasonml.github.io/en/try?rrjsx=true&reason=PQKgBALgFglgzmA7gewE4GsEmAKAEQCMAvAExEDMeOYYAPgHxgBScAdAMoSowB2A5qzgAHADYwIACjxE8ASmp1WzNiOR8A3DhyhIsBCgxwANJGTIw2fMTKUFAWkYtWqjVp0AjAK4Rd8MABNkAFM4HgByH0ttcABPZE8wAGMAQx5IEJ9oP0RxKDBPHkTkAFtioJ4IXj4rUgoqGgZlDi4qwVFxKRl5Ggcml01sIA)

[code for the proof](
https://gist.github.com/ryuheechul/017c37cabeb4de786b9213b3081f4c7d#file-fastpipeissue-re)
```re
/* this works */
"1=2=3"
  |> Js.String.split("=")
  |. Js.log;

/* this works, too */
"1=2=3"
  -> Js.log;

/* but the code below doesn't */
/* you can test this with uncommenting
"1=2=3"
  |> Js.String.split("=")
  -> Js.log;
*/
```

ReasonML ver: 3.3.2

**Comment by bloodyowl** [comment] 2018-10-29 15:31
this is because `->` isn't just sugar for `|.`, it has a higher precedence.

```reason
"1=2=3"
  |> Js.String.split("=")
  -> Js.log;
```

is parsed as 

```reason
"1=2=3"
  |> (
     /* the following expression logs the curried function, and returns unit, not a function */
    Js.String.split("=") |. Js.log
  );
```


which is a type error, you need to wrap the expression in parens:

```reason
("1=2=3" |> Js.String.split("="))
  -> Js.log;
```

if you reformat the correct example with `|.`, that's what you'll get.

**Comment by IwanKaramazow** [comment] 2018-10-29 20:57
Yes, for now `->` has higher precedence than `|.`.
```reason
("1=2=3" |> Js.String.split("="))->Js.log;
```
This is indeed the correct solution.
Will leave this open, the precedence of `->`  is pretty counterintuitive.
I think we can address this.

**Comment by ryuheechul** [comment] 2018-11-07 09:54
@bloodyowl thanks for the good explanation.
@IwanKaramazow Yes, I agree it can be counterintuitive unless the code writer know how actually `->` works as described by @bloodyowl.

So I hope it should either the explanation to be added in [the document page](https://reasonml.github.io/docs/en/fast-pipe#docsNav) or the fast pipe works more intuitive to avoid the confusion.

And I personally hope to see `->` gets to work just like `|.` to be able to code simpler.

**Comment by bloodyowl** [comment] 2018-11-07 12:57
AFAIK the main motivation for the precedence is to be able to do things like `event->target##value` and `value->getWithDefault(x).name`

**Comment by slonoed** [comment] 2019-04-27 18:46
Is there any way to preserve `|.` when using refmt? 
When a chain has a mix of `->` and `|>` code became ugly.

**Comment by anmonteiro** [comment] 2019-12-01 22:03
Closing as "won't fix", as the precedence is by design.

**Closed by anmonteiro** 2019-12-01 22:03 UTC
Labels: Syntax
