### ISSUE TITLE
[refmt] Do not convert unicode strings

### ISSUE THREAD

**Issue by rauanmayemir** [facebook/reason#1778] opened 2018-01-24 17:25 UTC
`refmt` automatically turns strings like "└── " into this:

![image](https://user-images.githubusercontent.com/9691/35344521-5069ea3a-0168-11e8-80c3-ab5ce647b1d7.png)

Making it practically useless.

This is from `esy`, where we pinned to [28a8922](https://github.com/facebook/reason/commit/28a8922ed2c2c2b5b32dcf2d72e93f56361959df). (but the issue persists on the latest commit)

**Comment by Schmavery** [comment] 2018-01-24 17:35
Related: https://github.com/facebook/reason/issues/1384, #1053, #799

@jordwalke you said a while ago that this is a matter of finding the right unicode printing library. Do you have any idea of possible candidates that you would want someone to explore if they were to tackle this?

**Comment by hcarty** [comment] 2018-01-24 17:43
This doesn't occur with ocamlformat - any idea why the two would act differently?

**Comment by rauanmayemir** [comment] 2018-01-24 17:45
Apparently, a well-known issue.

Please consider bumping its priority. It correctly matches the input in switches, but makes the language unusable if your alphabet differences doesn't stop at `å, ä, ö`.

**Comment by rauanmayemir** [comment] 2018-01-24 17:53
How curious.

![image](https://user-images.githubusercontent.com/9691/35348232-6f4655ce-0172-11e8-9463-cec76791fbed.png)

**Comment by Schmavery** [comment] 2018-01-24 19:25
I did some more investigation.
I don't know much about the refmt internals, but as far as I can tell, we print out strings here: https://github.com/facebook/reason/blob/43146a22f95dd9ce10d407c6f251ed85541fcae8/src/reason-parser/reason_pprint_ast.ml#L2377

Here pp = Format.fprintf (but Printf.fprintf and sprintf etc as long as %S is used)
I believe the problem is that the %S formatter can't handle unicode properly. Presumably it does some faulty escaping or similar? I've tested this locally and it %S seem to reproduce the problem.

According to https://caml.inria.fr/pub/docs/manual-ocaml/libref/Printf.html, this is 
`S: convert a string argument to OCaml syntax (double quotes, escapes).`

Compare this to the line below https://github.com/facebook/reason/blob/43146a22f95dd9ce10d407c6f251ed85541fcae8/src/reason-parser/reason_pprint_ast.ml#L2378
Which does print properly (and doesn't use %S).

Hopefully someone smarter than me can advise: in this case, we want to reproduce what the user types, is there a need for additional escaping? Or are we lucky and can we simply replace this line with the following? (Call me a wishful thinker)
```ocaml
| Pconst_string (i, None) -> pp f "\"%s\"" i 
```

**Comment by hhugo** [comment] 2018-01-24 20:20
@Schmavery, you'll still need to escape double quotes.

**Comment by jordwalke** [comment] 2018-01-24 20:48
Is this all that’s needed: https://github.com/ocaml-ppx/ocamlformat/blob/2d973e38571f574b773809d5d02f155cf2782676/src/Fmt_ast.ml#L314

If someone fixes it quickly it will go out in the release

**Comment by hcarty** [comment] 2018-01-24 20:55
@jordwalke No, shoot - I was wrong.  ocamlformat has the same issue with unicode strings.

**Comment by IwanKaramazow** [comment] 2018-01-24 21:00
Did some investigation a while ago and as @Schmavery indicates: ocaml's Format scrambles the unicode with the way where printing.

**Comment by Schmavery** [comment] 2018-01-24 21:23
@jordwalke in my testing, `String.escaped` exhibits the same problem.
Can anyone explain why we need to parse in escape sequences when lexing rather than just keeping "\n" as two characters (for example)?

**Comment by IwanKaramazow** [comment] 2018-01-24 21:32
Because `String.length` would break otherwise.
Imagine `let x = "🙈"` encoded in utf8. The `🙈` is represented by multiple bytes,
4 to be exact, in utf8. I.e. `String.length x === 4`. 
If you write the literal notation for each byte, you get:
`let x = "\240\159\153\136";`
If you don't escape the literals, you'll get `String.length === 16`.

**Comment by Schmavery** [comment] 2018-01-24 21:34
@IwanKaramazow my mistake was only thinking about the context of reformatting, where this wouldn't matter (afaict). Obviously the string should be escaped at runtime. Thanks for explanation.

**Comment by jordwalke** [comment] 2018-01-24 22:40
" I guess it's because we want to conform to the ocaml AST definition which would presumably expect string in this form. Nevermind. Maybe if there's a way to keep the original string around (only for formatting)... "

Yes! We can do exactly what we do for comments, which is to keep the original comments around, separate from the AST. Then when printing strings, we can look up the original file content for that location range, and pull the strings from there instead of trying to print the contents that was stored in the AST.

We have a format called `reason_binary` that we can `--parse`/`--print` and it includes `(comments, AST)`. We could add a new format called `reason_binary_with_strings` which has `comments, AST, strings)`. This would be the form that the printer actually uses. We would merely keep the old form `reason_binary` so that we can perform upgrades from previous versions of Reason.
Feel free to take a shot at that one.

**Comment by hcarty** [comment] 2018-01-24 22:49
See #1780 for a very basic, **incomplete** attempt at using uutf to for better UTF-8 encoded string printing.

**Comment by hcarty** [comment] 2018-01-24 22:50
@jordwalke I think the challenge in going from escaped strings back to the original content is that some assumption about or detection of the original encoding needs to be performed.

**Comment by jordwalke** [comment] 2018-01-24 22:59
Thanks.

We could also just stuff the original bytes into a ppx attribute that is never printed couldn't we?

**Comment by hcarty** [comment] 2018-01-24 23:04
Yeah - I think your suggestion of pulling raw bytes from the original source file is the best way to ensure string literals stay exactly as they were originally.  That was the case I was thinking of when mistakenly thinking ocamlformat already solved this - if formatting is disabled for a file with `[@@@ocamlformat.disabled]` then the input is preserved exactly, leaving unicode and other manual formatting intact.

**Comment by jordwalke** [comment] 2018-01-24 23:10
I don't know much about mll, but is there a way to call "quoted_string" (which is how the `{| |}` strings are parsed), and then effectively run the `string(s)` function on the result:

https://github.com/facebook/reason/blob/master/src/reason-parser/reason_lexer.mll#L762

So that we can get both forms?

I would also suggest avoiding doing this when the `--print` is anything but `--print re`. (There's a configuration record we could use to store the mode so that the lexer can know what mode we're in).

**Comment by jberdine** [comment] 2018-01-25 20:41
FWIW, ocamlformat currently preserves unicode within literal `{|` `|}` strings, but not normal `"` `"` strings, since the bytes of literal strings are just passed straight through using `Format.pp_print_string`.

**Comment by Schmavery** [comment] 2018-03-17 23:06
This should be fixed by https://github.com/facebook/reason/pull/1838 ! 😄

**Comment by chenglou** [comment] 2018-03-28 23:03
Yep

**Closed by chenglou** 2018-03-28 23:03 UTC
