### ISSUE TITLE
Upgraded syntax throws error: Tuples must have at least 2 components

### ISSUE THREAD

**Issue by jlongster** [facebook/reason#1510] opened 2017-10-13 16:56 UTC
I upgraded from beta-v-1.13.3 to master today, and ran the refmt process to upgrade all of my syntax. Previously I was doing some thing like this (I hand-converted this to the old syntax for this issue, hopefully I didn't make any mistakes):

```
Yojson.pretty_to_string(`Assoc [("client_id", `String "hi")]);
```

The new refmt converted it to this:

```
Yojson.pretty_to_string(`Assoc([("client_id", `String("hi"))]));
```

But compiling it throws an error: `Error: broken invariant in parsetree: Tuples must have at least 2 components`.

The full command is: `ocamlfind ocamlc -thread -package core,cohttp.lwt,redis.lwt,yojson,uuidm,kaputt -g -bin-annot -pp "refmt --print binary" -o _build/self/run2 -I _build/self -c -impl src/run2.re`

`run2.re` has only that expression inside of it. refmt is definitely the updated one which I pinned from master:

```
% where refmt
/Users/james/.opam/4.04.2/bin/refmt
```

**Comment by chenglou** [comment] 2017-10-14 00:54
Small repro:

```reason
`Assoc(1);
```

This is parsed as

```
[
  structure_item (foo.re[1,0+0]..[1,0+10])
    Pstr_eval
    expression (foo.re[1,0+0]..[1,0+9])
      Pexp_variant "Assoc"
      Some
        expression (foo.re[1,0+6]..[1,0+9])
          Pexp_tuple
          [
            expression (foo.re[1,0+7]..[1,0+8])
              Pexp_constant Const_int 1
          ]
]
```

Previously we've parsed

```
`Assoc 1
```

As

```
[
  structure_item (foo.re[1,0+0]..[1,0+9])
    Pstr_eval
    expression (foo.re[1,0+0]..[1,0+8])
      Pexp_variant "Assoc"
      Some
        expression (foo.re[1,0+7]..[1,0+8])
          Pexp_constant Const_int 1
]
```

In contrast, the current `Assoc(1)` and previous `Assoc 1` are both parsed as:

```
[
  structure_item (foo.re[1,0+0]..[1,0+9])
    Pstr_eval
    expression (foo.re[1,0+0]..[1,0+8])
      attribute "explicit_arity"
        []
      Pexp_construct "Assoc" (foo.re[1,0+0]..[1,0+5])
      Some
        expression (foo.re[1,0+5]..[1,0+8])
          Pexp_tuple
          [
            expression (foo.re[1,0+6]..[1,0+7])
              Pexp_constant Const_int 1
          ]
]
```

I'm still a bit confused on when we should use a tuple + `explicit_arity`. @jordwalke?

**Comment by jlongster** [comment] 2017-10-14 02:48
Why do we require parens around the polymorphic variant expression? It's not like we're calling a function, so it seems like an option would be to drop the parens here (in my opinion, making it clearer in many cases) but require parens when needing to group the expression.

**Comment by chenglou** [comment] 2017-10-14 02:49
It's actually to evoke the fact that we're calling a function

**Comment by jlongster** [comment] 2017-10-14 03:00
Yeah, right now it turns this:

```
    Delete {
      uuid: json |> Util.member "uuid" |> Util.to_string,
      table: json |> Util.member "table" |> Util.to_string,
      rowId: json |> Util.member "rowId" |> Util.to_string
    }
```

into this:

```
    Delete(
      {
        uuid: json |> Util.member("uuid") |> Util.to_string,
        table: json |> Util.member("table") |> Util.to_string,
        rowId: json |> Util.member("rowId") |> Util.to_string
      }
    )
```

The printer could make the brackets "hug" the parens so they are on the same line so there's not so much vertical space added. But IMHO I've never though about them as function calls, but more as "tags" so the parens are unnecessary. But it's all subjective.

**Comment by chenglou** [comment] 2017-10-14 03:07
^ actually function application "hugging" is fixed by #1417. Didn't think of variant and poly variant. cc @IwanKaramazow

**Comment by jordwalke** [comment] 2017-10-14 08:09
> "I'm still a bit confused on when we should use a tuple + explicit_arity. @jordwalke?"

We should add [explicit_arity] on regular variants, not polymorphic variants, so it's largely not relevant to this github issue. (Explicit arity just means, "Hey ocaml, expect us to distinguish between `X(1,2)` and `X 1 2`)."

 In this case, the problem is that we need to not create a tuple around only one argument to a polymorphic variant. The same goes for regular variants, but I don't think we have a bug for regular variants.

Some more background about variants for anyone curious (feel free to stop reading).

**Regular variants:**
- Can have one argument, or "multiple arguments".
- If having one argument, that one argument can be a tuple.

**Polymorphic variants:**
- Only accept one argument.
- Of course that one argument can be a tuple.

**explicit_arity**
- Reason tags regular (not polymorphic) variants with `[@explicit_arity]` to make the type system a little more strict. This is not relevant when considering polymorphic variants.

**Comment by jordwalke** [comment] 2017-10-14 08:11
Looks like right here we need to only wrap in a tuple if there are more than one arguments:

https://github.com/facebook/reason/blob/master/src/reason_parser.mly#L2804

marking #goodfirsttask

**Comment by IwanKaramazow** [comment] 2017-10-14 10:23
I'll tackle the parsing & printing problem.

**Comment by chenglou** [comment] 2017-10-16 23:07
@jlongster tested, fixed

**Closed** 2017-10-16 23:06 UTC
Labels: GOOD FIRST TASK

**Comment by jlongster** [comment] 2017-10-17 17:28
Thanks y'all, I'll try master again soon!
