### ISSUE TITLE
[broken printing] refmt removes parens around a `->` fastpipe expression in jsx

### ISSUE THREAD

**Issue by jaredly** [facebook/reason#2199] opened 2018-09-25 16:25 UTC
```
let x = <div>
  {one(two)->three(four)->five}
</div>
```
becomes
```
let x = <div>
  one(two)->three(four)->five
</div>
```
becomes
```
let x = <div>
  one
  two->three
  four->five
</div>
```
Which is then broken.

**Comment by anmonteiro** [comment] 2018-09-25 16:37
I think this is by design. What's broken in this case?

Here's what I get:


```js
$ echo '<div>  (one(two))  (one->two)</div>;' | ./_build/install/default/bin/refmt
<div> {one(two)} one->two </div>;
```

**Comment by jaredly** [comment] 2018-09-25 17:40
I guess this is the broken part:
```
let x = <div>
  {one(two)->three(four)->five}
</div>
```
becomes
```
let x = <div>
  one(two)->three(four)->five
</div>
```
becomes
```
let x = <div>
  one
  two->three
  four->five
</div>
```

**Comment by anmonteiro** [comment] 2018-09-25 17:41
@jaredly you might be on an outdated version / pin.

On current master:

```js
$ echo 'let x = <div>  {one(two)->three(four)->five} </div>' | ./_build/install/default/bin/refmt
let x = <div> {one(two)->three(four)->five} </div>;
```

**Comment by IwanKaramazow** [comment] 2018-09-25 19:04
Fixed in master, new bs-platform release with upstreamed refmt will be at the end of the month. Bob busy with icfp. Gonna close this one, feel free to ping me with more questions.

**Closed by IwanKaramazow** 2018-09-25 19:04 UTC
Labels: KIND: BUG, Printer
