### ISSUE TITLE
Trouble with <*>

### ISSUE THREAD

**Issue by rostero1** [facebook/reason#1336] opened 2017-07-15 19:59 UTC
I'm having to escape the `*` in `<*>`, but when I do get an error on `module OptionApplicativeF: ApplicativeFunction ...`:  `Signature mismatch: The value '<\*>' is required but not provided.`  When I change `<*>` to something else, such as `<@>`, then I don't receive that error.

How can I get this to compile with `<*>`?

```
module type Functor = {type t 'a; let fmap: ('a => 'b) => t 'a => t 'b;};

module type ApplicativeFunctor = {
  include Functor;
  let pure: 'a => t 'a;
  let (<\*>): t ('a => 'b) => t 'a => t 'b;
  let (<$>): ('a => 'b) => t 'a => t 'b;
};

module OptionFunctor: Functor with type t 'a = option 'a = {
  type t 'a = option 'a;
  let fmap f =>
    fun
    | Some a => Some (f a)
    | _ => None;
};

module OptionApplicativeF: ApplicativeFunctor with type t 'a = option 'a = {
  include OptionFunctor;
  let pure x => Some x;
  let (<\*>) f a =>
    switch (f, a) {
    | (Some f, Some a) => Some (f a)
    | _ => None
    };
  let (<$>) = fmap;
};

module Demo1 (A: ApplicativeFunctor) => {
  include A;
  let double x => x * 2;
  let eg1 x => double <$> x;
  let eg2 x y => pure (+) <\*> x <\*> y;
  let eg3 x y => (+) <$> x <\*> y;
};

module OptionDemo1 = Demo1 OptionApplicativeF;
```

Code taken from and converted to .re:  https://blog.0branch.com/posts/2012-03-26-02-from-functor.html

**Comment by bassjacob** [comment] 2017-07-15 20:39
Will be a duplicate of the issue I raised at https://github.com/facebook/reason/issues/1308

We even changed <*> to the same thing to get around it. what are the odds? 😛

**Comment by bassjacob** [comment] 2017-07-15 20:45
the way that I'm getting around this atm is by using a prefix function, flip and (|>) to simulate an infix arg. so in this case

```
let flip f b a => f a b;
let fmap f o => ...;
let apply f o => ...;
let liftA2 f a1 a1 => fmap f a1 |> flip apply a2;
```

**Comment by chenglou** [comment] 2017-10-11 03:23
Fixed in master

**Closed by chenglou** 2017-10-11 03:23 UTC
